// Self-host Google Fonts (Anton + Inter, latin subset only).
// - Fetches Google's CSS with a Chrome UA so it serves WOFF2.
// - Keeps only the latin /*…*/ blocks (covers our content).
// - Downloads each woff2 to site/fonts/ with a stable filename.
// - Generates site/css/fonts.css with rewritten @font-face URLs.
// Re-runnable: re-run after Google updates a font version.
const fs = require('fs');
const path = require('path');
const https = require('https');

const FONTS_DIR = path.resolve(__dirname, '..', 'site', 'fonts');
const CSS_OUT   = path.resolve(__dirname, '..', 'site', 'css', 'fonts.css');
const SRC_URL   = 'https://fonts.googleapis.com/css2?family=Anton&family=Inter:wght@400;600;700&display=swap';
const UA        = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

if (!fs.existsSync(FONTS_DIR)) fs.mkdirSync(FONTS_DIR, { recursive: true });

function get(url, opts = {}) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { headers: { 'user-agent': UA, ...(opts.headers || {}) } }, res => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return resolve(get(res.headers.location, opts));
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => {
        const buf = Buffer.concat(chunks);
        resolve(opts.binary ? buf : buf.toString('utf8'));
      });
    });
    req.on('error', reject);
  });
}

(async () => {
  console.log('Fetching font CSS from Google…');
  const css = await get(SRC_URL);

  // Extract latin-only @font-face blocks. Each block is preceded by a /* xxx */ comment.
  const blocks = css.split(/\/\*\s*([a-z-]+)\s*\*\//);
  // After split, blocks alternate: [pre, name, body, name, body, ...]
  const latinBlocks = [];
  for (let i = 1; i < blocks.length; i += 2) {
    if (blocks[i] === 'latin') {
      const body = blocks[i + 1];
      const m = body.match(/@font-face\s*\{[\s\S]*?\}/);
      if (m) latinBlocks.push(m[0]);
    }
  }
  console.log('  Latin @font-face blocks: ' + latinBlocks.length);

  // For each block: extract family + weight + woff2 URL, download woff2, rewrite URL.
  const rewritten = [];
  for (const block of latinBlocks) {
    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const url    = (block.match(/url\(([^)]+)\)\s*format\('woff2'\)/) || [])[1];
    if (!family || !weight || !url) continue;

    const filename = (family.toLowerCase() + '-' + weight + '.woff2');
    const localPath = path.join(FONTS_DIR, filename);
    if (!fs.existsSync(localPath)) {
      process.stdout.write('  Downloading ' + filename + '…');
      const buf = await get(url, { binary: true });
      fs.writeFileSync(localPath, buf);
      console.log(' ' + buf.length + ' bytes');
    } else {
      console.log('  Already have ' + filename);
    }

    rewritten.push(
      '@font-face {\n' +
      '  font-family: \'' + family + '\';\n' +
      '  font-style: normal;\n' +
      '  font-weight: ' + weight + ';\n' +
      '  font-display: swap;\n' +
      '  src: url(\'/fonts/' + filename + '\') format(\'woff2\');\n' +
      '  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+20AC, U+2122, U+2212;\n' +
      '}'
    );
  }

  const out =
    '/* Self-hosted Google Fonts — generated by scripts/download-fonts.js.\n' +
    '   Source: ' + SRC_URL + '\n' +
    '   Re-run that script to refresh after Google updates a font version. */\n\n' +
    rewritten.join('\n\n') + '\n';

  fs.writeFileSync(CSS_OUT, out);
  console.log('\nWrote ' + path.relative(path.resolve(__dirname, '..'), CSS_OUT));
})();
